### ISSUE TITLE
VOFFICE Data Center ASN

### ISSUE THREAD

**Issue by MrGoraj** [X4BNet/lists_vpn#104]
ASN data center from VOFFICE is missing from the list.

There were accounts created by bots on my site with their ip, so it's worth adding to the list.

ASN: 37276

**Comment by CameronMunroe** [comment]
This looks to be an ISP?

https://bgp.he.net/AS37276

**Comment by MrGoraj** [comment]
I checked more precisely, and it is indeed an ISP without commercial/cloud services
