### ISSUE TITLE
Provide option to pull out select ASN's

### ISSUE THREAD

**Issue by Neldogz** [X4BNet/lists_vpn#14]
Is there a way to pull out all the network blocks that belong to a particular ASN?

Noticed that we are unable to install updates on our Linux servers out on Azure due to Microsoft's ASN being included in the list.

**Comment by splitice** [comment]
Not currently, PR welcome

**Comment by splitice** [comment]
https://github.com/X4BNet/lists_vpn/issues/138

Although your particular example is perfectly valid in the Datacenters file
