### ISSUE TITLE
UFINET Data Centers ASN

### ISSUE THREAD

**Issue by MrGoraj** [X4BNet/lists_vpn#140]
I registered bot activities on my site with an ip belonging to this company.

IPInfo io provides partially contradictory information, because with ASN it can display, “hosting” and with company, “ISP”

I looked at their site and the company's activities appear to be entirely commercial, with no services for ordinary customers

ASN: 52468, 265620

**Comment by splitice** [comment]
Added

**Comment by abdullahdevrel** [comment]
I work for IPinfo.

> IPInfo io provides partially contradictory information, because with ASN it can display, “hosting” and with company, “ISP”

- 52468: https://ipinfo.io/AS52468 (`as_type`: Hosting)
- 265620: https://ipinfo.io/AS265620 (`as_type`: ISP)


Context: https://community.ipinfo.io/t/hosting-vs-isp-how-we-decide-the-ip-connection-types/5521

In terms of AS52468, you can see that there are many hosted domains (https://ipinfo.io/AS52468#block-domains), which should give some context as to why we think they are a hosting service. When it comes to this type of network, where they provide both ISP and hosting services, we have to choose one. On the other hand, AS265620 only has one IP address with a hosted domain.

You provided the correct context here, which is to look deeper and look up the company-type and other information we have for further context.
