### ISSUE TITLE
Teleglobal Data Center

### ISSUE THREAD

**Issue by MrGoraj** [X4BNet/lists_vpn#158]
I registered suspicious traffic activity from their ip.

IPInfo shows ISP/business, but after checking the portfolio on the website, you can see that their offerings are aimed at commercial customers, such as VPNs, hosting, Data Centers, etc.

ASN:  208932

**Comment by CameronMunroe** [comment]
Looks to be a "russian" site, but hosted in hong kong. Maybe sanction busting?

**Comment by splitice** [comment]
Added
