### ISSUE TITLE
Yandex Cloud Data Centers

### ISSUE THREAD

**Issue by MrGoraj** [X4BNet/lists_vpn#160]
Data centers from Yandex Cloud are missing from the list

ASN: 200350, 208795

They will not block the traffic of Yandex search engine indexing bots, as these use IP ranges from AS13238 and AS208722

Source about YandexBot: https://yandex.ru/support/webmaster/ru/robot-workings/check-yandex-robots.html?lang=en

**Comment by splitice** [comment]
Done
