### ISSUE TITLE
Example VPN IP from Azure not detected

### ISSUE THREAD

**Issue by blinkybill** [X4BNet/lists_vpn#17]
Thanks for making this great repository guys. It looks like its not detecting some Azure? traffic atm:

e.g. **20.171.45.109**

https://www.ipqualityscore.com/vpn-ip-address-check/lookup/20.171.45.109

This is an example of an anonymized IP that we know is definitely malicious / posting harmful requests almost on a daily basis

**Comment by splitice** [comment]
#22 PRs welcome
