### ISSUE TITLE
AppStore/PlayStore IP List

### ISSUE THREAD

**Issue by S8D** [X4BNet/lists_vpn#21]
Please separate a separate list of AppStore and PlayStore server IPs.
Agree that users can download new VPN apps, but if they need to update existing apps (not VPN apps), it's a bit inconvenient. Please remove AS15169 from the general list.
http://asn.blawk.net/15169
Thank you!

**Comment by splitice** [comment]
Commits to improve the list building process, perhaps introducing a strict VPN networks list and a Server networks (that may host VPN or VPN services) list is welcome.

We will not be however removing networks that are commonly used for VPN products.
