### ISSUE TITLE
Introduce multiple lists

### ISSUE THREAD

**Issue by splitice** [X4BNet/lists_vpn#22]
Ideas for a suitable breakdown include my current theory of:

1. Server Networks (non eyeball)
2. VPN networks and Bad Server networks
3. VPN Networks

PRs welcome

**Comment by CameronMunroe** [comment]
Since the repo is named List_vpn, would a new repo be better?

**Comment by splitice** [comment]
I'm fine with lists_vpn being broken out, simply because it's less CI script maintenance and potentially just a matter of matrixes for the CI.

**Comment by CameronMunroe** [comment]
Then we want to remove most of the ASNs on this list? I ask because most of them are not directly VPNs but are rather datacenters. 

We could fork this repo, make it list_datacenters, and remove the proxy lists. 

We would then take this repo and remove the datacenter lists.

**Comment by splitice** [comment]
FYI this work has been started (https://github.com/X4BNet/lists_vpn/tree/experiment/split-list)

It will take me a while (it's not my highest priority currently).

The goal will be an output of  `output/vpn/ipv4.txt` with the existing `ipv4.txt` being maintained (for the sake of legacy) for the forseeable future (but not indefinately).

Once this is done we will be able to proceed to introduce a "noteyeball" list to include server (and other networks not assosiated with human eyeball users).

**Comment by splitice** [comment]
Completed via https://github.com/X4BNet/lists_vpn/pull/35

**Comment by splitice** [comment]
Closure to follow after list review, improvement and merge of related issues.

**Comment by splitice** [comment]
Closed
