### ISSUE TITLE
provider expressvpn

### ISSUE THREAD

**Issue by shaddai** [X4BNet/lists_vpn#24]
the expressvpn provider has ranges not listed in the list :
please check resultst of a whois search here :

PSINet, Inc. COGENT-154-6-16 (NET-154-6-0-0-1) 154.6.0.0 - 154.6.255.255
LogicWeb Inc. LOGICWEB-CGNT-NET-1 (NET-154-6-0-0-2) 154.6.0.0 - 154.6.255.255
**Private Customer EXPRESSVPN (NET-154-6-16-0-1) 154.6.16.0 - 154.6.31.255**

**Comment by splitice** [comment]
This list is built strictly using long term accurate automated data sources. Please open an automation pr if you have a way to pull in whois data.

**Comment by splitice** [comment]
Woud depend on https://github.com/X4BNet/lists_vpn/issues/137

This is also a good example as to why we dont list IP ranges. That range is now  "Raffles Tower - 11th Floor"

Rented ranges change hands between customers all the time.
