### ISSUE TITLE
add more IPs list

### ISSUE THREAD

**Issue by Daniel3356** [X4BNet/lists_vpn#25]
add from AWS : 18.133.220.0/30

*I'm not sure about the subnet mask

**Comment by CameronMunroe** [comment]
AWS has an API we could use for this.

https://ip-ranges.amazonaws.com/ip-ranges.json

**Comment by splitice** [comment]
At this time I'm not interested in blocking the whole of aws.

If this list is split up into non eyeballs/vpn.then this can be considered for a non eyeballs network list.

**Comment by CameronMunroe** [comment]
Dumb question time, why would we not want to block all of AWS? 

In theory these are simmilar to regular datacenters.

**Comment by splitice** [comment]
Aws has hundreds of services and due to its cost (particularly bandwidth) it's a poor choice for a self hosted VPN server.

**Comment by CameronMunroe** [comment]
Then we should probably close issue.

**Comment by Daniel3356** [comment]
I also have those too to add in the VPN list
Belgium
37.120.143.0/Unknown Subnetmask —> AWS
207.138.211.0/Unknown Subnetmask —> AWS
217.238.211.0/Unknown Subnetmask —> AWS

Australia
54.66.0.0/16 —> AWS
13.236.165.0/14 —> AWS
3.25.70.0/Unknown Subnetmask —> AWS

@CameronMunroe thank you for your list but there I ended `/Unknown Subnetmask` aren't in the list you provided

**Comment by splitice** [comment]
Banning the whole of aws (all services) is probably not ideal for most people.

**Comment by splitice** [comment]
One way we might accept IP ranges is if they have a secondary verification such as RDNS for long term inclusion.
