### ISSUE TITLE
Why are we blocking Korean Telecom?

### ISSUE THREAD

**Issue by CameronMunroe** [X4BNet/lists_vpn#26]
https://github.com/X4BNet/lists_vpn/blob/main/input/ASN.txt#L9

I noticed this in the ASN listing, and was unsure why this choice was made?

**Comment by splitice** [comment]
Submit a pr to remove, I agree

**Comment by CameronMunroe** [comment]
@splitice, done.

**Comment by splitice** [comment]
Accepted
