### ISSUE TITLE
ejrv new owner

### ISSUE THREAD

**Issue by CameronMunroe** [X4BNet/lists_vpn#28]
With their being a new owner for the ejrv account. Should we change the readme to remove the link to the old profile?

**Comment by splitice** [comment]
I'm not really sure what to make of that issue to be honest. Either way this list was based off that, I'm not super concerned.

**Comment by CameronMunroe** [comment]
We could remove the link to the old repo. Since we do not know what the new user will do with the repo.

**Comment by splitice** [comment]
On second thought I think I saw the risk. That seems like an acceptable compromise. My only objection was to ensure credit is attributed where credit is due.

**Comment by CameronMunroe** [comment]
Might also be able to close ticket number #23 with this request.

**Comment by splitice** [comment]
Works for me and agreed.
