### ISSUE TITLE
AS 8881 | 1&1 ISP out of Germany

### ISSUE THREAD

**Issue by CameronMunroe** [X4BNet/lists_vpn#31]
AS8881 looks to be more of a residential ISP instead of a hosting provider. 

Can we remove this?

References: 

https://www.1und1.net/
https://bgp.he.net/AS8881

**Comment by splitice** [comment]
1&1 previously was a large webhost.

Now their site redirects to
https://www.ionos.com/

Perhaps using AS8560

**Comment by CameronMunroe** [comment]
https://asn.ipinfo.app/AS8560

Looking at the details of this, that looks to be correct. Would you like me to replace 8881 with 8560?

**Comment by splitice** [comment]
I think that's the way to.go

**Comment by CameronMunroe** [comment]
Added to commit.
