### ISSUE TITLE
Mixed ASNs

### ISSUE THREAD

**Issue by CameronMunroe** [X4BNet/lists_vpn#36]
Looking at the new VPN/ASN list I see a few ASNs that aren't 100% VPN. 

For example: AS32751 # Octovpn / xbox VPN

https://asn.ipinfo.app/AS32751 :: Nuclear Fallout (NFO). 

NFO offers VPS / Dedicated and other servers. Should we still consider this a VPN?

**Comment by splitice** [comment]
TBD

Filtering on swip/pa could probably help here in the future

**Comment by CameronMunroe** [comment]
> TBD
> 
> Filtering on swip/pa could probably help here in the future

Can you explain further?

**Comment by splitice** [comment]
https://www.arin.net/blog/2018/05/03/which-swip-type-is-right-for-you/

**Comment by splitice** [comment]
I'm fine with a datacenter being included that contains VPNs in the datacenters list, but am cautious against the other way around.

Will not include a ASN in the datacenters list if it has substantial eyeball users.
