### ISSUE TITLE
Cannot find ASN list

### ISSUE THREAD

**Issue by vitich** [X4BNet/lists_vpn#39]
Where is it?
Thx!

**Comment by CameronMunroe** [comment]
It got moved to here: https://github.com/X4BNet/lists_vpn/blob/main/input/datacenter/ASN.txt

-and- 

https://github.com/X4BNet/lists_vpn/blob/main/input/vpn/ASN.txt

**Comment by vitich** [comment]
> It got moved to here:
> 
> https://github.com/X4BNet/lists_vpn/blob/main/input/datacenter/ASN.txt -and- https://github.com/X4BNet/lists_vpn/blob/main/input/vpn/ASN.txt

Thank you!
