### ISSUE TITLE
VPN IP not being blocked

### ISSUE THREAD

**Issue by pspiro** [X4BNet/lists_vpn#45]
I am using VeePN and simulating Amsterdam/Netherlands. 
It gives me an ip of 51.15.81.134 which is not in your list. Should it be added?
![image](https://user-images.githubusercontent.com/16025587/226698248-d6c5b8b0-70dc-44c8-97b7-5ef9b2b0601b.png)

**Comment by CameronMunroe** [comment]
I think we would need to find some automation to add these IPs. 

Generally the owner of the repo doesn't want to add one off IPs that can't be maintained and updated in the future.

**Comment by supahero1** [comment]
It is present as `51.15.0.0/16` in datacenters' file.

**Comment by JohnBetaro** [comment]
can you please tell me how did you add all there ips to your router or network ? it's a lot for a router and AdGuard DNS only block domains.

**Comment by CameronMunroe** [comment]
> can you please tell me how did you add all there ips to your router or network ? it's a lot for a router and AdGuard DNS only block domains.

What are you trying to do here?

**Comment by splitice** [comment]
AS16276 is present as a datacenter.
