### ISSUE TITLE
DigitalOcean VPN Service 

### ISSUE THREAD

**Issue by NextPancake401** [X4BNet/lists_vpn#50]
This IP was found hitting port 443 a bunch of times in a short time span; I assume they didn't get anything and moved on but still. It shows up as a DigitalOcean IP on the west coast of the US (source: https://whatismyipaddress.com/ip/167.71.159.131)
167.71.159.131

I'm not very good at providing more information, I'm sorry. My network primarily blocks IPs from most countries (everything but the USA) since our users are all US based. But we do get a handful of hits and pokes from US based VPN and proxy providers and this IP was the first one I saw that stayed longer than a few initial pokes. (more than 4 entries in the firewall logs).

**Comment by splitice** [comment]
Already in the datacenters list
