### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dinger1986** [X4BNet/lists_vpn#52]
Hello, I wanted to include this list in a project I am doing but wanted to check if it's permitted as there is no license published.

MIT might be appropriate?

Thanks

**Comment by splitice** [comment]
Thats a valid point. I think MIT would be appropriate mostly.

My only issue is that it mentions software in the license. Something that this is not.

I'll take suggestions from the community.

**Comment by dinger1986** [comment]
maybe creative commons then? Its funny cause alot of people use MIT on github and sometimes isnt really appropriate, thanks for replying though :)

**Comment by splitice** [comment]
We are all guilty of that. IANAL but MIT matches with my wishes.

**Comment by Pascal-Delange** [comment]
Hi,
Also interested here, for similar reasons :)

**Comment by rhofland** [comment]
Hi,

Also interested. Any updates?

**Comment by splitice** [comment]
A license has been added along with clarification on what "software" means in the context of the applied MIT license.
