### ISSUE TITLE
OVPN is missing?

### ISSUE THREAD

**Issue by AnderssonPeter** [X4BNet/lists_vpn#53]
I think ovpn is missing when using it I got the IP 217.64.148.123 but it does not seem to match any of the ip's in the vpn list.

**Comment by TheRedSpy15** [comment]
ovpn is just a configuration file for VPNs, not a VPN itself

**Comment by splitice** [comment]
I think he means OBN who do hosting in Sweden.

AS42675 can be added to the DC list. I'll do that.
