### ISSUE TITLE
Missing ASNS?

### ISSUE THREAD

**Issue by L0calH0st80** [X4BNet/lists_vpn#57]
Hello,
I can't find anything other than Ipv4 list, I remember I was here couple days ago and there was a list of ASNs.

**Comment by CameronMunroe** [comment]
https://github.com/X4BNet/lists_vpn/blob/main/input/datacenter/ASN.txt

You mean this?

**Comment by L0calH0st80** [comment]
Ahh, I see. I thought it would be in output. I was looking at the output. Thank you!
