### ISSUE TITLE
Privado VPN looks like low hanging fruit plus maybe some others

### ISSUE THREAD

**Issue by theloglizard** [X4BNet/lists_vpn#58]
Hi,

[Per wikipedia](https://en.wikipedia.org/wiki/PrivadoVPN) Privado VPN  provides VPN services and looks like low hanging fruit to add.They have an ASN -- AS 50525 and a quick query using the [Hurricane Electric web tool](https://bgp.he.net/search?search%5Bsearch%5D=privado&commit=Search) 

AS50525 | ASN | Privado Networks AG
-- | -- | --
91.148.232.0/22 | Route | Privado Networks Frankfurt
91.148.228.0/22 | Route | Privado Networks Amsterdam
91.148.224.0/22 | Route | Privado Networks Amsterdam
81.171.70.0/23 | Route | Privado.io Stockholm IP Block
81.171.63.0/24 | Route | Privado.io Mexico IP Block
81.171.62.0/24 | Route | Privado VPN IP Block
2a01:788:1000::/48 | Route | Privado Networks DC
2001:4de0:1006::/48 | Route | Privado Networks DC
2001:4de0:1005::/48 | Route | Privado Networks DC
2001:4de0:1004::/48 | Route | Privado Networks Amsterdam

There is also a pile of VPN looking things in [AS62651 --AS Name NETPROTECT-62651 registered to Strong Technology .](https://bgp.he.net/AS62651#_prefixes)  These appear related to Netprotect , and of Netprotect [Linked in says "Specialties: Smart DNS Solutions, Internet Privacy and Security, Smart VPN Solutions, and Anonymity"](https://www.linkedin.com/company/netprotect)
according to [Wikipedia](https://en.wikipedia.org/wiki/J2_Global#:~:text=StrongVPN%20is%20a%20commercial%20VPN,and%20was%20founded%20in%202005.), J2 Global owns Netprotect. Specifically, according  to the  website top10vpn, "[NetProtect, which is part of J2 Global (owner of Mashable, eFax, Ookla Speedtest, and PCMag, among others), acquired SaferVPN on Tuesday 23 July ](https://www.top10vpn.com/research/tech-giant-j2-globals-netprotect-acquires-safervpn/), so it all hangs together. The table below, courtesy of [Hurricane Electric](https://bgp.he.net/AS62651#_prefixes)

Prefix | Description
-- | --
69.16.147.0/24 | NP-DP-CPH (C09524753)
103.209.255.0/24 | STL-TLV-DP Shacham St 40 Petah Tikva, Israel
104.36.180.0/22 | STL-YYZ-SP (C08843978)
173.255.173.0/24 | STL-BOG-DP (C09090000)
176.67.82.0/24 |  
176.67.84.0/24 |  
176.67.87.0/24 |  
205.185.193.0/24 | NP-DUB-DP (C09451428)
216.131.72.0/23 | Netprotect (C07867418)
216.131.74.0/23 | Netprotect (C07867423)
216.131.76.0/23 | Netprotect (C07867426)
216.131.78.0/23 | Netprotect (C07867432)
216.131.80.0/23 | Netprotect (C07867433)
216.131.82.0/23 | STL-NYC-DP (C08836376)
216.131.87.0/24 | Netprotect (C07867436)
216.131.105.0/24 | NETPR-BRU-DP (C09698280)
216.131.108.0/24 | Netprotect (C07935446)
216.131.109.0/24 | Netprotect (C07935450)
216.131.110.0/24 | Netprotect (C07935452)
216.131.111.0/24 | Netprotect (C07939027)
216.131.112.0/24 | Netprotect (C07944121)

[Similarly from Hurricane Electric](https://bgp.he.net/AS54203#_prefixes), AS54203 has a large number of network ranges connected to Netprotect and Strong Technology

Prefix | Description
-- | --
36.255.205.0/24 | Strong Technology, LLC - Sydney
36.255.206.0/23 | Strong Technology, LLC - Tokyo
64.145.65.0/24 | Netprotect (C08103545)
64.145.67.0/24 | Netprotect (C08104378)
64.145.76.0/24 | Netprotect (C08104462)
64.145.79.0/24 | Netprotect (C08104464)
64.145.90.0/23 | Netprotect (C08233404)
64.145.93.0/24 | Netprotect (C08233399)
64.145.94.0/24 | Netprotect (C08233405)
69.16.145.0/24 | Netprotect (C08123322)
69.16.157.0/24 | Netprotect (C08123324)
69.16.172.0/24 | Netprotect (C08123330)
98.158.112.0/20 | STL-NYC-SP (C08843923)
103.209.252.0/24 | Strong Technology, LLC - Hong Kong
104.36.176.0/23 | STL-IAD-SP (C08843953)
104.36.178.0/23 | STL-MIA-SP (C08843957)
108.171.104.0/21 | STL-MIA-SP (C08843969)
108.171.112.0/20 | STL-NYC-SP (C08843971)
173.195.0.0/20 | STL-NYC-SP (C08843994)
173.245.202.0/24 | Netprotect (C08233411)
173.245.203.0/24 | Netprotect (C08233415)
173.245.206.0/23 | Netprotect (C08233440)
173.245.209.0/24 | Netprotect (C08104473)
173.245.211.0/24 | Netprotect (C08104544)
173.245.217.0/24 | Netprotect (C08104624)
173.245.219.0/24 | Netprotect (C08104626)
173.255.160.0/21 | STL-NYC-SP (C08844184)
173.255.170.0/23 | STL-BOS-SP (C08844188)
173.255.172.0/24 | STL-MSP-SP (C08844190)
173.255.176.0/20 | STL-MIA-SP (C08844227)
176.67.80.0/23 |  
176.67.85.0/24 |  
176.67.86.0/24 |  
185.91.120.0/22 | Overplay, Inc
185.147.212.0/24 |  
185.147.213.0/24 |  
185.147.214.0/24 |  
185.147.215.0/24 |  
199.33.71.0/24 | Netprotect (C08233512)
199.127.248.0/21 | STL-NYC-SP (C08844281)
205.185.192.0/24 | Netprotect (C08233445)
205.185.199.0/24 | Netprotect (C08137774)
205.185.209.0/24 | Netprotect (C08137775)
205.185.214.0/24 | Netprotect (C08137776)
205.185.221.0/24 | Netprotect (C08233452)
205.185.222.0/24 | Netprotect (C08233462)
205.185.223.0/24 | Netprotect (C08233466)
209.107.192.0/23 | Netprotect (C08110865)
209.107.195.0/24 | Netprotect (C08279799)
209.107.196.0/24 | Netprotect (C08233480)
209.107.204.0/24 | NETPROTECT-MIA-SP (C08833847)
209.107.210.0/24 | Netprotect (C08110881)
209.107.212.0/24 | Netprotect (C08110884)
209.107.214.0/24 | Netprotect (C08110886)
209.107.216.0/24 | Netprotect (C08110891)
209.234.248.0/24 | Netprotect (C08110892)
216.131.88.0/23 | Netprotect (C07940844)
216.131.114.0/24 | Netprotect (C07940538)
216.131.116.0/23 | Netprotect (C07940544)
216.131.118.0/24 | STL-DTW-SP (C08857194)
216.131.120.0/24 | STL-STL-SP (C08843908)
216.151.180.0/24 | NETPROTECT-NYC-SP (C08835420)
216.151.183.0/24 | Netprotect (C08233492)
216.151.191.0/24 | Netprotect (C08116714)
216.169.132.0/24 | Black Oak Computers Inc - Miami (C04683825)
216.169.133.0/24 | Black Oak Computers Inc - Washington DC (C04859350)
216.169.134.0/24 | Strong Technology, LLC.
216.169.135.0/24 | Black Oak Computers Inc - Washington DC (C04683835)
216.169.136.0/21 | Strong Technology, LLC.

I don't know what your criteria, are, but, for example, one can connect to some of the addresses, above and see they are owned by StrongVPN. For a specific example, if you visit http://205.185.192.83/ you see this:
<img width="989" alt="image" src="https://github.com/X4BNet/lists_vpn/assets/55997192/d121be34-20d0-42a4-9e7e-56045ff438e9">

**Comment by splitice** [comment]
I'm happy to accept a PR for these, the research looks good and low collateral damage.

**Comment by splitice** [comment]
Added
