### ISSUE TITLE
Nigerian ISP ASNs included

### ISSUE THREAD

**Issue by praemon** [X4BNet/lists_vpn#65]
So I've been testing the list against some well known traffic and some results are coming up that seems like they shouldn't. Namely:

AS36873 # VNL1-AS, NG --- Airtel mobile ISP
AS36920 # KKON, NG --- Also an ISP, although they do seem to do hosting. However, I'd imagine it should be a much smaller range as it's covering their entire IP range
AS29465 # VCG-AS, NG --- MTN mobile ISP

Any reason I can't submit a PR to remove these?

**Comment by CameronMunroe** [comment]
https://bgp.he.net/AS36873 -- This looks to be a mobile provider from my checks, at least per the website.

https://bgp.he.net/AS36920 -- Looks to be an ISP as well. 

https://bgp.he.net/AS29465 -- Another mobile ISP.
