### ISSUE TITLE
Missing IPs due to ASN conversion build script

### ISSUE THREAD

**Issue by praemon** [X4BNet/lists_vpn#66]
I noticed that certain IPs weren't matching even though the ASN is listed. An example is:

AS9009 # M247, GB (NordVPN)

Test IP: 92.119.177.22

I thought initially the problem was with the source https://iptoasn.com/ since it's no longer being updated (a separate issue that likely needs to be looked at with https://github.com/X4BNet/lists_vpn/issues/12 ), however, I found the issue is as follows:

In the build script there is the following use of ipcalc:

`awk '{if($3 == '${asn:2}') print "ipcalc -rn "$1"-"$2" | tail -n1"}' /tmp/asndb.tsv | bash >> /tmp/asn-processed.txt`

It uses "tail" to only get the last result. The problem is the result in asndb.tsv covering this IP is:

92.119.176.0	92.119.181.255	9009	RO	M247

ipcalc's result is then:

```
ipcalc -rn 92.119.176.0-92.119.181.255
deaggregate 92.119.176.0 - 92.119.181.255
92.119.176.0/22
92.119.180.0/23
```

To have proper coverage it needs both 92.119.176.0/22 and 92.119.180.0/23 and not just the last one.

Unless there's a specific reason for just getting the last line, I propose something like this to allow all ranges but exclude the line with "deaggregate":

`awk '{if($3 == '${asn:2}') print "ipcalc -rn "$1"-"$2}' /tmp/asndb.tsv | bash | grep -v "deaggregate" >> /tmp/asn-processed.txt`

This obviously will have a fairly big impact by including far more IPs than before, but I believe it's more correct?

**Comment by splitice** [comment]
I'll test your idea. It sounds like a nice find.

**Comment by splitice** [comment]
`tail -n+2` is more correct.

Its only the first line that actually needs to be excluded

**Comment by splitice** [comment]
This has been fixed.
