### ISSUE TITLE
ASN proposal

### ISSUE THREAD

**Issue by MrBoombastic** [X4BNet/lists_vpn#9]
Could you add Nvidia's IPs? It is ASN `AS50889`. People are using Nvidia's GeForce Now cloud gaming app as a VPN.
Example IP: `77.111.251.160`.
![image](https://user-images.githubusercontent.com/18630357/151425665-0df4bfb6-95c8-4d81-8adf-cc46baf86623.png)

There are possibly more IP blocks to add: https://bgp.he.net/search?search%5Bsearch%5D=NVIDIA+Ltd&commit=Search

**Comment by splitice** [comment]
Controversial considering it will probably block gamers and be to the detriment of gaming services.

**Comment by FannyLoi** [comment]
Forgive me for the question, but how would adding this ASN block gamers?  Would gamers, just like all other Internet users direct connect to resources rather than through a VPN, even if it's hosted in the Nvidia cloud?  I may be missing something really obvious and if so, please correct me!

**Comment by splitice** [comment]
Closing this as it would block any gamers using Nvidias gaming cloud for its intended purpose. Which for now would be more a problem than a solution.

If you disagree a fork running the same CI scripts can be made with this ASN.
